- DC-SLES-pci-dss
- xml/art_pci-dss.xml
- xml/common_gfdl1.2_i.xml
- xml/product-entities.ent
- xml/security_pcidss.xml
TODO:
* Correct the respective docserv config file.
> Add pci dss

- xml/art_security_pcidss.xml
Update metadata for 'Editing Source' and 'Report Documentation Bug' links in HTML.  
* SLE writers sync call minutes 2022-03-24
> Update metadata for PCI-DSS Guide

- DC-SLES-pci-dss
We want to switch to the new 3-column layout. This PR uses the new stylesheets.
*no maintenance branches yet*
> Use suse2022-ns stylesheets for en-us

- xml/art_security_pcidss.xml
Integrated proofing corrections for the PCI DSS Guide from VT.
> PCI DSS Guide proofing integration

- container-guide/xml/containers-get.xml
Fix BCI-189
* bsc#...
* jsc#SLE-...
> Add release-stage values

- container-guide/xml/containers-bci.xml
> Add note on update

- container-guide/xml/containers-support.xml
> Remove tiers, simplify support

- suseconnect-tracking/xml/art_suseconnect_tracking.xml
Mention the benefits of this new feature at the beginning of the article.
> Update SUSEConnect keep-alive docs

- trento/xml/article_sap_trento.xml
Corrections to commands in platform independent section under Problem Analysis.
* bsc#...
* jsc#SLE-...
> Problem analysis command corrections

- trento/xml/article_sap_trento.xml
Correction on scenario dump procedure
* bsc#...
* jsc#SLE-...
> Correction on scenario dump procedure

- trento/xml/article_sap_trento.xml
Small enhancement to describe SSH key generation as Trento Server requirements
Here is the relevant section as HTML screenshot:
https://confluence.suse.com/display/TRNT/2022-11-16+Trento+Documentation
> Describe SSH key generation for Trento Server requirement

- trento/xml/article_sap_trento.xml
Trento version 1.2.0 provides configuration checks for HANA scale-up performance optimized clusters deployed on on-premise bare metal platforms, including KVM and Nutanix.
* bsc#...
* jsc#SLE-...
> Support for on-premise bare metal

- container-guide/adoc/attributes-generic.adoc
- container-guide/adoc/containers-bci.adoc
Add container-suseconnect
* BCI-185
> Add container-suseconnect

- pcidss/xml/art_security_pcidss.xml
Introduce `&productnameshort;` entity as discussed in SLE Writers Call on 2022-11-21.
* DOCTEAM-828
> Introduce &productnameshort; entity

- container-guide/adoc/attributes-product.adoc
- container-guide/adoc/book-container-docinfo.xml
Introduce `productnameshort` entity as discussed in SLE Writers Call on 2022-11-21.
Dima, I'm not completely sure about the abbrevicated product name.
* DOCTEAM-828
> Introduce productnameshort attribute

- trento/xml/article_sap_trento.xml
Telemetry data also collected for community version
* bsc#...
* jsc#SLE-...
> Telemetry data also collected for community version

- trento/xml/article_sap_trento.xml
Trento premium is available at not extra cost for SLES for SAP 15 (SP1 and higher) subscribers
* bsc#...
* jsc#SLE-...
> Trento premium cost

- trento/xml/article_sap_trento.xml
Adding a section explaining how to open a support case for Trento in the SUSE Customer Center.
* bsc#...
* jsc#SLE-...
> Opening a support case for Trento

- container-guide/adoc/containers-podman-overview.adoc
Fix DOCTEAM-528
* bsc#...
* jsc#SLE-...
> Rootless Podman fix

- container-guide/adoc/containers-bci.adoc
Fix SLE-22420
* bsc#...
* jsc#SLE-...
> Add SLE_BCI note

- sap-ha-support/xml/art-sap-ha-support.xml
Changed the support status of `susTkOver.py` from `Planned` to `Supported but undocumented`.
* bsc#1209202
* jsc#DOCTEAM-918
> Update support status of susTkOver.py

- container-guide/adoc/containers-basics.adoc
- container-guide/adoc/containers-tools.adoc
Containers new content for Basics and Tools
> Containers new content for Basics and Tools

- container-guide/adoc/containers-building-images.adoc
- container-guide/adoc/containers-tools.adoc
Adding link to docker doc for distribution mirroring
> Adding link to docker doc for distribution mirroring

- trento/xml/article_sap_trento.xml
Additional changes required after initial testing following release of new version
* bsc#...
* jsc#SLE-...
> Additional changes for version 2.0.0

- container-guide/adoc/containers-verify.adoc
> Revise, extend verification

- container-guide/adoc/containers-verify.adoc
Fixes rendering of "note" elements in the doc.
> containers-verify: fix "note" rendering

- container-guide/adoc/containers-bci.adoc
Add a section describing application BCIs
* DOCTEAM-890
> Application BCIs

- trento/xml/article_sap_trento.xml
Update memory requirements from 2GB to 3GB.
Update memory requirements from 2GB to 3GB.
* bsc#...
* jsc#SLE-...
> Update memory requirements

- container-guide/adoc/book-container.adoc
- container-guide/adoc/containers-basics.adoc
- container-guide/adoc/containers-bci.adoc
- container-guide/adoc/containers-orchestration.adoc
- container-guide/adoc/containers-podman-overview.adoc
- container-guide/adoc/containers-registration-repositories.adoc
- container-guide/adoc/containers-support.adoc
- container-guide/adoc/containers-tools.adoc
Integrate proofing corrections for the Container Guide from proofing drop 3.
> Container Guide: integrate proofing corrections

- sap-ha-support/images/src/svg/cost-optimized.svg
- sap-ha-support/images/src/svg/ensa1.svg
- sap-ha-support/images/src/svg/ensa2.svg
- sap-ha-support/images/src/svg/multi-target.svg
- sap-ha-support/images/src/svg/multi-tier.svg
- sap-ha-support/images/src/svg/overview-sr-single-nodes.svg
- sap-ha-support/images/src/svg/pacemaker-cluster.svg
- sap-ha-support/images/src/svg/performance-optimized.svg
- sap-ha-support/xml/art-sap-ha-support.xml
Overhaul all graphics contained in thid document and include plain SVG instead of PNG.
> Graphics overhaul 2023

- pcidss/.editorconfig
- pcidss/.gitignore
- pcidss/doc-kit.conf
- pcidss/xml/generic-entities.ent
- pcidss/xml/network-entities.ent
- pcidss/xml/product-entities.ent
Rebase PCI-DSS Guide on `docbook5-book` flavor of doc-kit (https://github.com/openSUSE/doc-kit/) to allow to update common files from there in the future.
> PCI-DSS: adjust doc-kit to docbook5 flavor

- container-guide/images/src/svg/pods_architecture.svg
Just an Inkscape facelift for the pods_architecture pic.
> facelift for pods_architecture.svg

- trento/xml/article_sap_trento.xml
Minor corrections
Minor corrections
* bsc#...
* jsc#SLE-...
> Minor corrections

- trento/xml/article_sap_trento.xml
A section providing a compatibility matrix between Trento Server and Trento Agents
https://confluence.suse.com/display/TRNT/2023-08-16+Trento+Documentation
> New section of Trento compatibility matrix

- trento/xml/article_sap_trento.xml
A section describing the different versions available of Trento along with their most important user-facing features.
* https://confluence.suse.com/display/TRNT/2023-08-16+Trento+Documentation
> New section of Trento version history

- sap-ha-support/xml/art-sap-ha-support.xml
It's time for updates to this overview, provided by Sherry Yu in collaboration with engineering. 
* bsc#1213965
> Update SAP HA overview

- suseconnect-visibility/xml/art_suseconnect_visibility.xml
Bugzilla link and URL to source code were broken. 
* reported internally by Olli Tuominen
> suseconnect-visibility: fix feedback options

- trento/xml/article_sap_trento.xml
Proof reading of previous PRs and other minor changes.
* bsc#...
* jsc#SLE-...
> Proofreading of previous PRs and other minor changes.

- container-guide/concepts/containers-podman.xml
Fix a minor untruth about what cgroup v1 allow or not (in our distro).
> container-guid: Fix cgroup v1 user access

- sap-ha-support/xml/art-sap-ha-support.xml
Added support info for SAP HANA NSE.
* bsc#1215320
* jsc#DOCTEAM-1112
> Add HANA NSE support info

- trento/xml/article_sap_trento.xml
> Trento support plugin options

- sap-ha-support/images/src/svg/ensa1.svg
- sap-ha-support/images/src/svg/ensa2.svg
Updated the SLE HA product name in two graphics.
* jsc#DOCTEAM-1133
> Update SLE HA product name in graphics

- container-guide/concepts/containers-podman.xml
The section about the new netavark features was not entirely technically correct, hence the following suggestion to improve it.
cc @danishprakash
> Reformulate section about netavark-firewalld-reload.service

- trento/xml/article_sap_trento.xml
> Release date of version 2.2.0

- container-guide/concepts/containers-build-app-images.xml
- container-guide/concepts/containers-docker.xml
- container-guide/concepts/containers-orchestration.xml
- container-guide/concepts/containers-terms.xml
- container-guide/concepts/containers-tools.xml
Fix broken links and replace `http` by `https` protocol where feasible.
- see also https://github.com/SUSE/doc-sle/pull/1635
> Container Guide: fix links

- openscap/xml/article_openscap.xml
- stig/xml/article_stig.xml
> DOCTEAM-1171 - Before new content: Rebase with main, Vale fixes, XML formatting

- sap-ha-support/xml/art-sap-ha-support.xml
Adding a new link to a doc for this script, as requested. 
* bsc#1219260
* jsc#DOCTEAM-1250
> Add doc links for HADR provider hook scripts

- stig/xml/article_stig.xml
Added syntax highlighting for xml snippet
* bsc#...
* jsc#SLE-...
> Added syntax highlighting for xml snippet

- container-guide/concepts/containers-bci-intro.xml
- container-guide/concepts/containers-bci-language.xml
- container-guide/concepts/containers-bci-lifecycle.xml
- container-guide/concepts/containers-tools.xml
Rename Language Stack BCI to Development Stack BCI
* PED-7645
> Dev stack BCI

- container-guide/concepts/containers-podman.xml
Fix PED-8304
* bsc#...
* jsc#SLE-...
> Docker Hub add

- container-guide/common/generic-entities.ent
- container-guide/common/license_gfdl1.2.xml
- container-guide/doc-kit.conf
- container-guide/templates/articles/assembly.asm.xml
see title
* no feature request, just a required update before the localization drop
> Container Guide: doc-kit run (fetch updates)

- pcidss/doc-kit.conf
- pcidss/xml/common_license_gfdl1.2.xml
- pcidss/xml/generic-entities.ent
see title
* no feature request, just a necessary update before localization drop
> PCI-DSS: doc-kit run (fetch updates)

- trento/xml/article_sap_trento.xml
To include HANA scale-out clusters, diskless SBD clusters and maintenance status
* change#2
* https://confluence.suse.com/x/_YA0WQ
> Trento-change#2: Revamp of HANA cluster discovery

- trento/xml/article_sap_trento.xml
Manual and automated with Ansible playbook
* change#3
* https://confluence.suse.com/x/_YA0WQ
> Trento-change#3: Non-K8s based installation of Trento Server

- trento/xml/article_sap_trento.xml
> Trento v2.3.0 change#10

- trento/xml/article_sap_trento.xml
Fix structure and disable empty section
> Correct structure & disable section

- container-guide/concepts/containers-bci-intro.xml
- container-guide/concepts/containers-bci-lifecycle.xml
- container-guide/concepts/containers-tools.xml
The scope of this PR is limited to removing officially/official words.
[DOCTEAM-1375)](https://jira.suse.com/browse/DOCTEAM-1375)
> [WIP]DOCTEAM-1375: remove officially/official

- trento/xml/article_sap_trento.xml
Release of version 2.3.2.
* bsc#...
* jsc#SLE-...
> Release of version 2.3.2

- container-guide/concepts/containers-verify.xml
Fix DOCTEAM-1524
* bsc#...
* jsc#SLE-...
> Verify charts w/Cosign

- sap-ha-support/xml/art-sap-ha-support.xml
Minor correction for HADR provider hook scripts. Wording approved by Fabian.
* bsc#1213315
* jsc#DOCTEAM-1046
> Correct legacy hook script versions

- container-guide/l10n/zh-cn/xml/Container-guide.xml
Fix localized metadata:
- based on additions for English (https://github.com/SUSE/doc-unversioned/pull/145)
- based on the spreadsheet with localized metadata for all guides in zh-cn
> Container Guide: fix localized metadata

- suseconnect-visibility/DC-SLE-suseconnect-visibility
- suseconnect-visibility/xml/art_suseconnect_visibility.xml
Remove unnecessary profiling attributes.
n/a
> Remove profiling os=article information

- container-guide/concepts/containers-support.xml
Add a section listing the platforms BCIs are tested on.
* PED-10688
> Add test platforms

- container-guide/concepts/containers-docker-registry.xml
Refresh the section about deploying a registry to use the SLE BCI Registry image.
cc @danishprakash @dirkmueller
> Refresh the documentation about deploying a registry

- trento/xml/article_sap_trento.xml
Correct a typo of the file extension for the Trento agent.
No
> article_sap_trento.xml: Fix issues with agent filename and amqp url example

- trento/migration/systemd-install.md
- trento/xml/systemd-install.xml
Different location for Trento self-signed certificate
This PR can be merged/published once it has been reviewed. No need to wait for the release of the next version.
> Different location for Trento self-signed certificate

- trento/migration/container-install.md
- trento/xml/container-install.xml
Need to make copy of keys used during containerized installation.
This PR can me merged/published once it has been reviewed. No need to wait for the release of the next version.
> Need to make copy of keys using during containerized installation

- trento/xml/article_sap_trento.xml
Fix spelling of assembly/meta title.
[jsc#DOCTEAM-1611](https://jira.suse.com/browse/DOCTEAM-1611)
> Trento: assembly/meta title -> title style

- container-guide/concepts/containers-podman.xml
> Add audit note. Fix bsc-1238515

- trento/.gitignore
- trento/doc-kit.conf
- trento/xml/generic-entities.ent
> Trento - doc-kit run (fetch updates)

- container-guide/concepts/containers-verify.xml
It can be down for a week and doesn't help with the integrity check to refer to an external site for fetching the verification key
* bsc#...
* jsc#SLE-...
> Avoid dependency on ftp.suse.com

- trento/adoc/trento-container-install.adoc
- trento/adoc/trento-install-server.adoc
- trento/adoc/trento-systemd-install.adoc
> Fix TRNT-3888
