xml/art_security_pcidss.xml
We claim that PCI-DSS 3.2 is the current version, but 4.0 has been released end of March, see https://blog.pcisecuritystandards.org/pci-dss-v4-0-resource-hub
This PR only updates the version number and release date but no content whatsoever. The [wikipedia article](https://en.wikipedia.org/wiki/Payment_Card_Industry_Data_Security_Standard#History) suggests more work (firewall, 2FA) is necessary.
=> PCI-DSS 4.0 is out

trento/xml/article_sap_trento.xml
Variable &productname displays as "PRODUCT" in current Trento Documentation. Replacing it with &sles4sap;&nbsp; so that "SUSE Linux Enterprise Server for SAP Applicatons" shows instead.
* bsc#...
* jsc#SLE-...
=> Replacing &productname; with &sles4sap;&nbsp;

trento/xml/article_sap_trento.xml
Specify K3s version v1.24.6+k3s1 in the K3s installation command (there is a issue with latest version of K3s (v1.25.3+k3s1) and if you issue the installation of K3s without specifying a version, the latter installation of Trento Server fails (see https://bugzilla.suse.com/show_bug.cgi?id=1205171).
* bsc#...
* jsc#SLE-...
=> Specific K3s version

container-guide/adoc/book-container-docinfo.xml, container-guide/adoc/book-container.adoc
The Container Guide misses some Docmanager tags for Bugzilla. This leads to broken "Report bug" link.
If we want to use Bugzilla, there is a product "Documentation". However, you can't select "Container".
* SD-103231 (request new "Container" component in Bugzilla)
=> Add missing Docmanager tags for Container Guide

trento/xml/article_sap_trento.xml
Add sentence for the section "Trento Server requirements" when using K3s.
Here is the relevant section as HTML screenshot:
Taken from https://confluence.suse.com/display/TRNT/2022-11-16+Trento+Documentation
=> Add Trento Server requirement for K3s

openscap/xml/article_openscap.xml
Remediation option with Ansible was missing. Viktor suggested to add this during a tech review (for the related STIG paper).
=> OpenSCAP: add section on remediation with Ansible

trento/xml/article_sap_trento.xml
Trento is only supported on K8s based on a x86_64 architecture
* bsc#...
* jsc#SLE-...
=> K8s based on x86_64 architecture

kubevirt/xml/art-kubevirt.xml
kubevirt: Fix the VMI manifest example
Remove the redundant field 'status: {}' from the manifest as it causes validation errors.
* bsc#...
* jsc#SLE-...
=> Fixes for KubeVirt doc

trento/xml/article_sap_trento.xml
Right syntax for parameter FACTS_SERVICE_URL
Right syntax for agent configuration parameter FACTS_SERVICE_URL and requirement for AMQP connectivity from the agent host to the trento server.
* bsc#...
* jsc#SLE-...
=> Right syntax for parameter FACTS_SERVICE_URL

container-guide/adoc/containers-bci.adoc, container-guide/adoc/containers-orchestration.adoc, container-guide/adoc/containers-registration-repositories.adoc
`daps linkcheck` reported some broken links which have been fixed. In addition, turned some links into SP-independent links (as per style guide recommendation, see https://documentation.suse.com/style/current/single-html/docu_styleguide/#sec-link-to-susecom)
=> Container Guide: fix broken links

trento/xml/article_sap_trento.xml
Corrections to the problem analysis section
Corrections to the problem analysis section.
* bsc#...
* jsc#SLE-...
=> Corrections to the problem analysis section

trento/xml/article_sap_trento.xml
Revision on installation, update and uninstallation procedures.
=> Review of installation, update and uninstallation procedures

sap-ha-support/xml/art-sap-ha-support.xml
Added the following row to _Table 4: Supported configurations for S/4HANA based on ABAP Platform 1809 or newer_ and _Table 5: Supported configurations for SAP NetWeaver based on ABAP Platform 1709 or older_:
* bsc#1214376
* jsc#DOCTEAM-1090
=> Add rows for ENSA1 and 2 with SAP Web Dispatcher

suseconnect-visibility/xml/art_suseconnect_visibility.xml
This information was missing from the table.
=> Add total memory to SCC data capture

container-guide/concepts/containers-bci-labels.xml
We were suggesting to use `jq` for json parsing, but podman and skopeo support go templates which do a good enough job by themselves.
cc @danishprakash
=> Don't use jq for json parsing, skopeo & podman support this natively

trento/xml/article_sap_trento.xml
adding to the trento agent requirement section the fact that the machine id must be unique in the registered environment
=> need for different machine ids

container-guide/articles/Container-guide.asm.xml
Update spelling of book title as agreed with @dmpop ('Container guide' ->  'Container Guide').  
* Fixes one of the issues mentioned in https://github.com/SUSE/doc-unversioned/pull/99
=> title: use entity with correct spelling

suseconnect-visibility/xml/art_suseconnect_visibility.xml
SUSEConnect doesn't capture hardware CPUs, but logical or virtual CPUs (i.e., the result of sockets * cores per socket * threads per core). This PR updates the documentation to use the precise naming.
* bsc#...
* jsc#SLE-...
=> Rename CPUs => vCPUs

sap-ha-support/xml/art-sap-ha-support.xml, trento/xml/article_sap_trento.xml
In case we need pull these two in for the first portal release (as part of sles-sap), they got the full metadata treatment. What isn't fixable at this point is the productname/version dilemma for unversioned stuff. I've put in the data as it is laid out in the docserv config. 
@tomschr Not sure when's the right time to merge this.
* bsc#...
* jsc#SLE-...
=> Add missing metadata for trento/ha-support

openscap/xml/article_openscap.xml
Removed the old unsupported PCI-DSS version 3.2.1 from the Compliance documentation.
* [jsc#DOCTEAM-1428](https://jira.suse.com/browse/DOCTEAM-1428)
> **NOTE**: For the remaining part of the JIRA issue, I will hand it over to Karl or Ornella to update the SUMA docs.
=> Removed the old unsupported PCI-DSS version 3.2.1 from the Compliance documentation

trento/xml/article_sap_trento.xml
This pr aims to update the provided project link in chapter "**16 More information**".
The current link redirects the reader to the archived version of Trento.
This change points to Trento web, the current main part of the project, where the reader is welcomed by a README which provides a good overview over what Trento is.
=> Update outdated project link in  trento documentation

trento/xml/article_sap_trento.xml
Trento version 2.3.1 requires flag trento-web.trentoWebOrigin for helm installation
Trento version 2.3.1  requires flag trento-web.trentoWebOrigin for helm installation
=> Trento version 2.3.1 new flag required for helm installation

container-guide/concepts/containers-bci-intro.xml, container-guide/concepts/containers-bci-understand.xml, container-guide/concepts/containers-build-app-images.xml, container-guide/concepts/containers-build-images.xml, container-guide/concepts/containers-docker-registry.xml, container-guide/concepts/containers-docker.xml, container-guide/concepts/containers-intro.xml, container-guide/concepts/containers-orchestration.xml, container-guide/concepts/containers-podman.xml, container-guide/concepts/containers-repo-reg.xml, container-guide/concepts/containers-support.xml, container-guide/concepts/containers-tools.xml
Integrate proofing corrections for the Container Guide from proofing drop 3.
There is an image missing in the PDF build:
PDF page 56
File: concepts/containers-orchestration.xml
Source:
```
<informalfigure>
<mediaobject>
<imageobject>
<imagedata fileref="pods_architecture.png" width="80.0%"/>
</imageobject>
<textobject><phrase>Image</phrase></textobject>
</mediaobject>
</informalfigure>
```
=> Container Guide: integrate proofing corrections

trento/xml/article_sap_trento.xml
This pr adds the missing required TRENTO_DOMAIN env in the helm cmd for this [bug fix ](https://github.com/trento-project/web/pull/2671) which was renamed to [TRENTO_WEB_ORIGIN ](https://github.com/trento-project/web/pull/2682) to the official documentation.
Without TRENTO_WEB_ORIGIN the helm cmd fails.
=> Add missing Trento Web Origin Configuration to Helm Command

pcidss/xml/art_security_pcidss.xml
Add metadata from 'Product Docs Metadata per deliverable' spreadsheet. 
Added a revhistory based on commit log. 
=> PCI DSS: add metadata

openscap/xml/article_openscap.xml
Add metadata from 'Product Docs Metadata per deliverable' spreadsheet. 
Added a revhistory based on commit log. 
=> OpenSCAP: add metadata

stig/xml/article_stig.xml
Add metadata from 'Product Docs Metadata per deliverable' spreadsheet. 
Added a revhistory based on commit log. 
=> STIG: add metadata

suseconnect-visibility/xml/art_suseconnect_visibility.xml
As part of our last epic, we have introduced more parameters which are being gathered and sent to scc.suse.com. The public documentation should reflect these new parameters being sent.
=> Update hardware information gathered by SUSEConnect

scc-hypervisor-collector/xml/art-scc-hypervisor-collector.xml, suseconnect-visibility/xml/art_suseconnect_visibility.xml, system-uptime-tracking/xml/art_system-uptime-tracking.xml
Add metadata from 'Product Docs Metadata per deliverable' spreadsheet. 
Added a stub revhistory based on docserv-config logs.
=> SCC articles: add metadata

container-guide/articles/Container-guide.asm.xml
Add metadata from 'Product Docs Metadata per deliverable' spreadsheet.
- Do we want to treat the guide as 'Smart Doc' or as 'Product & Solution Documentation'? metadata is not complete yet (and a bit mixed currently)
- If 'Product & Solution Docs': which tasks to associate it with?
- If Smart Docs: which productname and productversions?
=> Container Guide: add metadata

sap-ha-support/xml/art-sap-ha-support.xml
Previously, there were separate rows for "SAPHanaSR.py scale-up" and "SAPHanaSR.py scale-out". However, we already have different columns for Scale-up and Scale-out. So, I've moved the content into a single row: 
* bsc#1213315
* jsc#DOCTEAM-1046
=> Single row for SAPHanaSR.py

trento/xml/article_sap_trento.xml
This PR should be merged and publish right away once reviewed and approved. 
Changes to compatibility matrix:
- removal of last row (trento agent 2.3.2)
- change agent version 2.3.1 with 2.3.0
- add check mark for agent version 2.3.0 and server version 2.3.3
* bsc#...
* jsc#SLE-...
=> Correct compatibility matrix

pcidss/l10n/zh-cn/xml/art_security_pcidss.xml
Fix localized metadata for PCI DSS Guide:
- based on additions for English (https://github.com/SUSE/doc-unversioned/pull/160)
- based on the spreadsheet with localized metadata for all guides in zh-cn
=> PCI-DSS Guide: fix localized metadata

trento/xml/article_sap_trento.xml
The Trento Support Config plugin has been moved to a new repo and the download path has changed. This PR replaces the old path with the new one.
This PR can be merged as soon as it is reviewed and approved. No need to wait for next version.
* bsc#...
* jsc#SLE-...
=> New path for Trento Support Config plugin

trento/xml/article_sap_trento.xml
To be reviewed and published immediately (no need to wait for new version).
Trento server has been available as a set of rpm packages since version 2.3 but the lifecycle section does not mention it.
* bsc#...
* jsc#SLE-...
=> Updates regarding nonK8s version of Trento Server

trento/xml/article_sap_trento.xml
This PR can be merged/published once reviewed, no need to wait for the new version of Trento to be out.
The current content of the Uninstalling Trento Server section is specific to Kubernetes deployment. We are just adding a note saying so.
=> Update to the Trento Server Uninstalling Section

trento/xml/article_sap_trento.xml
An Improved explanation of the right value of the facts-service-url parameter in the agent configuration file.
Once reviewed, this PR should be merged and published (no need to wait for new version release).
=> Improved explanation of facts-service-url parameter

trento/xml/article_sap_trento.xml
This PR is to be reviewed and merged/published right away. No need to wait for the next version of Trento.
It extends section Reporting a Problem to the systemd and containerized scenario. It also clarifies that the Trento Support Plugin and the Scenario dump scripts are specific to the Kubernetes deployment
=> Updates to the Reporting a Problem and Problem Analysis Sections

trento/migration/systemd-install.md, trento/xml/article_sap_trento.xml, trento/xml/systemd-install.xml
Just a couple of minor corrections before the release of the new version of Trento: 1) In the Uninstall section replace "update" with "uninstall" 2) In the systemd deployment section, removal of the first nginx reload step since the certificate does not exist yet and the reload will make nginx crash.
To be reviewed, merged and published ASAP.
=> Minor corrections before release of new version

trento/xml/article_sap_trento.xml
This PR documents the user mgmt feature that will be available with the next version of Trento, which is to be released by the end of September, beginning of October. It is to be reviewed but not merged until the new version is out.
* bsc#...
* jsc#SLE-...
=> New section for user mgmt feature

trento/xml/article_sap_trento.xml
Not to be merged/published until new version is out!
General re-writing of the section to include also systemd and containerized scenarios.
See https://github.com/SUSE/doc-unversioned/pull/172#discussion_r1827549395 to solve this after #165 is merged.
=> Update to the Trento Server update section

trento/xml/article_sap_trento.xml
This PR isto be reviewed ahead of the release of version 2.4. But it is not to be merged/published until the new version is out.
It delivers a new section for the Activity Log that will be available with the new version.
The new section should be located after the also new SSO integration section and before the section about performing configuration checks.
=> New section for activity log

trento/migration/container-install.md, trento/xml/container-install.xml
This is part of the new version if the Trento release and therefore should go
together with the other PRs by @abravosuse.  I didn't see his existing PRs
before opening this one.  Sorry for the confusion this might have introduced
----
As part of the recent updates to [Trento](https://github.com/trento-project),
we separated the Trento checks into it's own
[package & repo](https://github.com/trento-project/checks)
The separation requires updates to the container installation.  This allows the
user to update the checks separately from Wanda.  An update to the systemd
/ RPM instructions is not required, because Wanda pulls the newly created
RPM as part of its dependencies 
I will make at least two more PRs in the following days, because I plan to remove
all references of Trento Premium from …
=> Update Trento Container Installation Instructions

trento/xml/article_sap_trento.xml
This PR is to be reviewed but not merged/published until the new version of Trento is out.
The section explaining how to use trento-server-installer is removed since it is no longer a supported tool.
=> trento-server-installer no longer supported

trento/xml/article_sap_trento.xml
This PR is to be reviewed but cannot be merged/published until the new version of Trento is out.
It adds a new section describing how to update the configuration checks in a Trento installation.
=> Updating Trento Checks

trento/xml/article_sap_trento.xml, trento/xml/trento-lifecycle.xml
=> Trento lifecycle include

trento/xml/article_sap_trento.xml, trento/xml/html/rh-article-trento.html, trento/xml/trento-intro.xml, trento/xml/trento-web-console.xml
A temporary workaround that replaces SUMA with SUSE Multi-Linux Manager until a new version of dic-kit is ready.
=> SUMA to SUSE Multi-Linux Manager workaround

trento/migration/systemd-install.md, trento/xml/systemd-install.xml
Add new `/api/v1/groups` and `/api/v1/operations` endpoints nginx rule to nginx configuration.
**To be merged once we have release `2.5.0` ready**.
The operations part might not be really needed there, but well, it is not harmful and we just have some work done in advance.
If we want to be super picky, we can remove the operations part and it after 2.5.0 release
=> Add operations endpoint nginx rule

suseconnect-visibility/xml/art_suseconnect_visibility.xml
With the upcoming version 5.1, **SUSE Manager** will be renamed to **SUSE Multi-Linux Manager** (already released SuMa versions keep their name and their documentation URLs).
The unversioned docs also should reflect the product name change. 
Also, the 'generic' URL `https://documentation.suse.com/suma` (which always redirects to the docs for the latest released SuMa version) will be replaced with `https://documentation.suse.com/multi-linux-manager` moving forward.
https://jira.suse.com/browse/DOCTEAM-1754
=> suseconnect: SuMa to SMLM

sap-ha-support/xml/product-entities.ent
SLES for SAP Applications ->  SLES for SAP applications (on request of the product manager). 
I thought we had fixed this with https://github.com/openSUSE/doc-kit/pull/108 and the doc-kit run afterwards, but by chance I spotted the 'old' spelling in the PDF and saw that another entity from `product-entities.ent` was used here (which is product-specific and not under doc-kit control). Hence this PR.
=> SLES for SAP applications: fix productname spelling

pcidss/xml/art_security_pcidss.xml
With the upcoming version 5.1, **SUSE Manager** will be renamed to **SUSE Multi-Linux Manager** (already released SuMa versions keep their name and their documentation URLs).
The unversioned docs also should reflect the product name change. 
Also, the 'generic' URL `https://documentation.suse.com/suma` (which always redirects to the docs for the latest released SuMa version) will be replaced with `https://documentation.suse.com/multi-linux-manager` moving forward.
https://jira.suse.com/browse/DOCTEAM-1754
=> PCIDSS: SuMa to SMLM

trento/adoc/checks_customization.adoc
This Pr is a template for the upcoming checks customization feature for trento web.
The pr provides an adoc document which can be used in the main article.
=> Add checks customization feature documentation
